version: '3'
networks:
  my-network:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: bosc-nginx
    ports: 
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - my-network
    depends_on:
      - rails-one

  mysql-service:
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    image: 'mysql:5.6'
    container_name: bosc-mysql
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my-network

  rails-one:
    image: bjornnborg/budget-on-sight
    container_name: bosc-rails
    networks:
      - my-network
    ports:
      - '3000:3000'
    depends_on:
      - mysql-service
